=== Ishamael/fg-xsl-compo/compos.dtd
<!ELEMENT fleets (category*)>
<!ELEMENT category (name, compo*)>
<!ELEMENT compo (name, ships, strength*, weakness*)>
<!ATTLIST compo min-pow CDATA #IMPLIED>
<!ATTLIST compo min-tech CDATA #IMPLIED>
<!ATTLIST compo faction (Brotherhood|GalacticDiplomaticOffice|AutonomousNetwork) #IMPLIED>
<!ATTLIST compo type (aggressive|defensive|mixed) "mixed">
<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT ships (front, back?)>
<!ELEMENT front (ship*)>
<!ELEMENT back (ship*)>
<!ELEMENT ship (#PCDATA)>
<!ATTLIST ship amount (1|2|3|4|5) #REQUIRED>
<!ELEMENT strength (#PCDATA)>
<!ELEMENT weakness (#PCDATA)>

=== Ishamael/fg-xsl-compo/compos.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="compos.xsl" type="text/xsl" title="Default style"?>
<!DOCTYPE fleets PUBLIC "-//FGDOC//DTD FleetCompos XML//EN" "./compos.dtd">
<fleets>
	<category>
		<name>Lukc</name>
		<compo min-tech="4" min-pow="1k">
			<name>CorZerGar+HellSent</name>
			<ships>
				<front>
					<ship amount="2">Corsairs</ship>
					<ship amount="2">Zeros</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="4">Hellcats</ship>
					<ship amount="4">Sentinels</ship>
				</back>
			</ships>
		</compo>
	</category>
	<category>
		<name>Defensive fleets</name>
		<compo min-tech="8" min-pow="20k" type="defensive">
			<name>Shield</name>
			<ships>
				<front>
					<ship amount="2">Templars</ship>
					<ship amount="2">Eclipses</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="2">Valkiries</ship>
				</back>
			</ships>
		</compo>
	</category>
	<category>
		<name>Brute fleets</name>
		<compo min-tech="4" min-pow="1k" faction="Brotherhood">
			<name>Full Spectres</name>
			<ships>
				<front>
					<ship amount="1">Spectres</ship>
					<ship amount="3">Hellcats</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="5">Shadows</ship>
				</back>
			</ships>
			<strength>Full Oblivion</strength>
			<weakness>Sentinels</weakness>
		</compo>
		<compo faction="AutonomousNetwork" type="aggressive">
			<name>Full Ph≈ìnix</name>
			<ships>
				<front>
					<ship amount="1">Phoenixes</ship>
				</front>
			</ships>
			<weakness>Everything</weakness>
		</compo>
	</category>
	<category>
		<name>Just shit</name>
		<compo>
			<name>Error 404.1</name>
			<ships>
				<front>
					<ship amount="2">Spectres</ship>
					<ship amount="5">Guardians</ship>
					<ship amount="2">Liberties</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Furies</ship>
				</back>
			</ships>
		</compo>
		<compo>
			<name>Error 404.2</name>
			<ships>
				<front>
					<ship amount="4">Templars</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Raptors</ship>
				</back>
			</ships>
		</compo>
		<compo>
			<name>Error 404.3</name>
			<ships>
				<front>
					<ship amount="4">Templars</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Furies</ship>
				</back>
			</ships>
		</compo>
	</category>
</fleets>
